#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogWebApp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BlogDb")]
	public partial class BlogDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertkategoriler(kategoriler instance);
    partial void Updatekategoriler(kategoriler instance);
    partial void Deletekategoriler(kategoriler instance);
    partial void Insertyoneticiler(yoneticiler instance);
    partial void Updateyoneticiler(yoneticiler instance);
    partial void Deleteyoneticiler(yoneticiler instance);
    partial void Insertmakaleler(makaleler instance);
    partial void Updatemakaleler(makaleler instance);
    partial void Deletemakaleler(makaleler instance);
    partial void Insertyorumlar(yorumlar instance);
    partial void Updateyorumlar(yorumlar instance);
    partial void Deleteyorumlar(yorumlar instance);
    #endregion
		
		public BlogDbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BlogDbConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BlogDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BlogDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BlogDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BlogDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<kategoriler> kategorilers
		{
			get
			{
				return this.GetTable<kategoriler>();
			}
		}
		
		public System.Data.Linq.Table<yoneticiler> yoneticilers
		{
			get
			{
				return this.GetTable<yoneticiler>();
			}
		}
		
		public System.Data.Linq.Table<makaleler> makalelers
		{
			get
			{
				return this.GetTable<makaleler>();
			}
		}
		
		public System.Data.Linq.Table<yorumlar> yorumlars
		{
			get
			{
				return this.GetTable<yorumlar>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kategoriler")]
	public partial class kategoriler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _kategoriAdi;
		
		private string _urlsefKatAdi;
		
		private EntitySet<makaleler> _makalelers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnkategoriAdiChanging(string value);
    partial void OnkategoriAdiChanged();
    partial void OnurlsefKatAdiChanging(string value);
    partial void OnurlsefKatAdiChanged();
    #endregion
		
		public kategoriler()
		{
			this._makalelers = new EntitySet<makaleler>(new Action<makaleler>(this.attach_makalelers), new Action<makaleler>(this.detach_makalelers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kategoriAdi", DbType="NVarChar(50)")]
		public string kategoriAdi
		{
			get
			{
				return this._kategoriAdi;
			}
			set
			{
				if ((this._kategoriAdi != value))
				{
					this.OnkategoriAdiChanging(value);
					this.SendPropertyChanging();
					this._kategoriAdi = value;
					this.SendPropertyChanged("kategoriAdi");
					this.OnkategoriAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlsefKatAdi", DbType="NVarChar(50)")]
		public string urlsefKatAdi
		{
			get
			{
				return this._urlsefKatAdi;
			}
			set
			{
				if ((this._urlsefKatAdi != value))
				{
					this.OnurlsefKatAdiChanging(value);
					this.SendPropertyChanging();
					this._urlsefKatAdi = value;
					this.SendPropertyChanged("urlsefKatAdi");
					this.OnurlsefKatAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kategoriler_makaleler", Storage="_makalelers", ThisKey="ID", OtherKey="kategoriID")]
		public EntitySet<makaleler> makalelers
		{
			get
			{
				return this._makalelers;
			}
			set
			{
				this._makalelers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_makalelers(makaleler entity)
		{
			this.SendPropertyChanging();
			entity.kategoriler = this;
		}
		
		private void detach_makalelers(makaleler entity)
		{
			this.SendPropertyChanging();
			entity.kategoriler = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.yoneticiler")]
	public partial class yoneticiler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _kullaniciAdi;
		
		private string _Sifre;
		
		private string _Email;
		
		private string _adi;
		
		private string _soyadi;
		
		private EntitySet<makaleler> _makalelers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnkullaniciAdiChanging(string value);
    partial void OnkullaniciAdiChanged();
    partial void OnSifreChanging(string value);
    partial void OnSifreChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnadiChanging(string value);
    partial void OnadiChanged();
    partial void OnsoyadiChanging(string value);
    partial void OnsoyadiChanged();
    #endregion
		
		public yoneticiler()
		{
			this._makalelers = new EntitySet<makaleler>(new Action<makaleler>(this.attach_makalelers), new Action<makaleler>(this.detach_makalelers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullaniciAdi", DbType="NVarChar(50)")]
		public string kullaniciAdi
		{
			get
			{
				return this._kullaniciAdi;
			}
			set
			{
				if ((this._kullaniciAdi != value))
				{
					this.OnkullaniciAdiChanging(value);
					this.SendPropertyChanging();
					this._kullaniciAdi = value;
					this.SendPropertyChanged("kullaniciAdi");
					this.OnkullaniciAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="NVarChar(50)")]
		public string Sifre
		{
			get
			{
				return this._Sifre;
			}
			set
			{
				if ((this._Sifre != value))
				{
					this.OnSifreChanging(value);
					this.SendPropertyChanging();
					this._Sifre = value;
					this.SendPropertyChanged("Sifre");
					this.OnSifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adi", DbType="NVarChar(50)")]
		public string adi
		{
			get
			{
				return this._adi;
			}
			set
			{
				if ((this._adi != value))
				{
					this.OnadiChanging(value);
					this.SendPropertyChanging();
					this._adi = value;
					this.SendPropertyChanged("adi");
					this.OnadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soyadi", DbType="NVarChar(50)")]
		public string soyadi
		{
			get
			{
				return this._soyadi;
			}
			set
			{
				if ((this._soyadi != value))
				{
					this.OnsoyadiChanging(value);
					this.SendPropertyChanging();
					this._soyadi = value;
					this.SendPropertyChanged("soyadi");
					this.OnsoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="yoneticiler_makaleler", Storage="_makalelers", ThisKey="ID", OtherKey="yazarID")]
		public EntitySet<makaleler> makalelers
		{
			get
			{
				return this._makalelers;
			}
			set
			{
				this._makalelers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_makalelers(makaleler entity)
		{
			this.SendPropertyChanging();
			entity.yoneticiler = this;
		}
		
		private void detach_makalelers(makaleler entity)
		{
			this.SendPropertyChanging();
			entity.yoneticiler = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.makaleler")]
	public partial class makaleler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _makaleAdi;
		
		private string _makaleKisaAciklama;
		
		private string _makaleDescription;
		
		private string _makaleKeyword;
		
		private string _makaleTitle;
		
		private System.Nullable<int> _yazarID;
		
		private System.Nullable<int> _kategoriID;
		
		private string _makale;
		
		private string _resim;
		
		private EntityRef<kategoriler> _kategoriler;
		
		private EntityRef<yoneticiler> _yoneticiler;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnmakaleAdiChanging(string value);
    partial void OnmakaleAdiChanged();
    partial void OnmakaleKisaAciklamaChanging(string value);
    partial void OnmakaleKisaAciklamaChanged();
    partial void OnmakaleDescriptionChanging(string value);
    partial void OnmakaleDescriptionChanged();
    partial void OnmakaleKeywordChanging(string value);
    partial void OnmakaleKeywordChanged();
    partial void OnmakaleTitleChanging(string value);
    partial void OnmakaleTitleChanged();
    partial void OnyazarIDChanging(System.Nullable<int> value);
    partial void OnyazarIDChanged();
    partial void OnkategoriIDChanging(System.Nullable<int> value);
    partial void OnkategoriIDChanged();
    partial void OnmakaleChanging(string value);
    partial void OnmakaleChanged();
    partial void OnresimChanging(string value);
    partial void OnresimChanged();
    #endregion
		
		public makaleler()
		{
			this._kategoriler = default(EntityRef<kategoriler>);
			this._yoneticiler = default(EntityRef<yoneticiler>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makaleAdi", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string makaleAdi
		{
			get
			{
				return this._makaleAdi;
			}
			set
			{
				if ((this._makaleAdi != value))
				{
					this.OnmakaleAdiChanging(value);
					this.SendPropertyChanging();
					this._makaleAdi = value;
					this.SendPropertyChanged("makaleAdi");
					this.OnmakaleAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makaleKisaAciklama", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string makaleKisaAciklama
		{
			get
			{
				return this._makaleKisaAciklama;
			}
			set
			{
				if ((this._makaleKisaAciklama != value))
				{
					this.OnmakaleKisaAciklamaChanging(value);
					this.SendPropertyChanging();
					this._makaleKisaAciklama = value;
					this.SendPropertyChanged("makaleKisaAciklama");
					this.OnmakaleKisaAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makaleDescription", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string makaleDescription
		{
			get
			{
				return this._makaleDescription;
			}
			set
			{
				if ((this._makaleDescription != value))
				{
					this.OnmakaleDescriptionChanging(value);
					this.SendPropertyChanging();
					this._makaleDescription = value;
					this.SendPropertyChanged("makaleDescription");
					this.OnmakaleDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makaleKeyword", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string makaleKeyword
		{
			get
			{
				return this._makaleKeyword;
			}
			set
			{
				if ((this._makaleKeyword != value))
				{
					this.OnmakaleKeywordChanging(value);
					this.SendPropertyChanging();
					this._makaleKeyword = value;
					this.SendPropertyChanged("makaleKeyword");
					this.OnmakaleKeywordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makaleTitle", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string makaleTitle
		{
			get
			{
				return this._makaleTitle;
			}
			set
			{
				if ((this._makaleTitle != value))
				{
					this.OnmakaleTitleChanging(value);
					this.SendPropertyChanging();
					this._makaleTitle = value;
					this.SendPropertyChanged("makaleTitle");
					this.OnmakaleTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yazarID", DbType="Int")]
		public System.Nullable<int> yazarID
		{
			get
			{
				return this._yazarID;
			}
			set
			{
				if ((this._yazarID != value))
				{
					if (this._yoneticiler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnyazarIDChanging(value);
					this.SendPropertyChanging();
					this._yazarID = value;
					this.SendPropertyChanged("yazarID");
					this.OnyazarIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kategoriID", DbType="Int")]
		public System.Nullable<int> kategoriID
		{
			get
			{
				return this._kategoriID;
			}
			set
			{
				if ((this._kategoriID != value))
				{
					if (this._kategoriler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkategoriIDChanging(value);
					this.SendPropertyChanging();
					this._kategoriID = value;
					this.SendPropertyChanged("kategoriID");
					this.OnkategoriIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makale", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string makale
		{
			get
			{
				return this._makale;
			}
			set
			{
				if ((this._makale != value))
				{
					this.OnmakaleChanging(value);
					this.SendPropertyChanging();
					this._makale = value;
					this.SendPropertyChanged("makale");
					this.OnmakaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resim", DbType="NVarChar(250)")]
		public string resim
		{
			get
			{
				return this._resim;
			}
			set
			{
				if ((this._resim != value))
				{
					this.OnresimChanging(value);
					this.SendPropertyChanging();
					this._resim = value;
					this.SendPropertyChanged("resim");
					this.OnresimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kategoriler_makaleler", Storage="_kategoriler", ThisKey="kategoriID", OtherKey="ID", IsForeignKey=true)]
		public kategoriler kategoriler
		{
			get
			{
				return this._kategoriler.Entity;
			}
			set
			{
				kategoriler previousValue = this._kategoriler.Entity;
				if (((previousValue != value) 
							|| (this._kategoriler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kategoriler.Entity = null;
						previousValue.makalelers.Remove(this);
					}
					this._kategoriler.Entity = value;
					if ((value != null))
					{
						value.makalelers.Add(this);
						this._kategoriID = value.ID;
					}
					else
					{
						this._kategoriID = default(Nullable<int>);
					}
					this.SendPropertyChanged("kategoriler");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="yoneticiler_makaleler", Storage="_yoneticiler", ThisKey="yazarID", OtherKey="ID", IsForeignKey=true)]
		public yoneticiler yoneticiler
		{
			get
			{
				return this._yoneticiler.Entity;
			}
			set
			{
				yoneticiler previousValue = this._yoneticiler.Entity;
				if (((previousValue != value) 
							|| (this._yoneticiler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._yoneticiler.Entity = null;
						previousValue.makalelers.Remove(this);
					}
					this._yoneticiler.Entity = value;
					if ((value != null))
					{
						value.makalelers.Add(this);
						this._yazarID = value.ID;
					}
					else
					{
						this._yazarID = default(Nullable<int>);
					}
					this.SendPropertyChanged("yoneticiler");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.yorumlar")]
	public partial class yorumlar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _makaleID;
		
		private string _isim;
		
		private string _email;
		
		private string _mesaj;
		
		private System.Nullable<int> _onay;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnmakaleIDChanging(System.Nullable<int> value);
    partial void OnmakaleIDChanged();
    partial void OnisimChanging(string value);
    partial void OnisimChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnmesajChanging(string value);
    partial void OnmesajChanged();
    partial void OnonayChanging(System.Nullable<int> value);
    partial void OnonayChanged();
    #endregion
		
		public yorumlar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makaleID", DbType="Int")]
		public System.Nullable<int> makaleID
		{
			get
			{
				return this._makaleID;
			}
			set
			{
				if ((this._makaleID != value))
				{
					this.OnmakaleIDChanging(value);
					this.SendPropertyChanging();
					this._makaleID = value;
					this.SendPropertyChanged("makaleID");
					this.OnmakaleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isim", DbType="NVarChar(50)")]
		public string isim
		{
			get
			{
				return this._isim;
			}
			set
			{
				if ((this._isim != value))
				{
					this.OnisimChanging(value);
					this.SendPropertyChanging();
					this._isim = value;
					this.SendPropertyChanged("isim");
					this.OnisimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mesaj", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string mesaj
		{
			get
			{
				return this._mesaj;
			}
			set
			{
				if ((this._mesaj != value))
				{
					this.OnmesajChanging(value);
					this.SendPropertyChanging();
					this._mesaj = value;
					this.SendPropertyChanged("mesaj");
					this.OnmesajChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_onay", DbType="Int")]
		public System.Nullable<int> onay
		{
			get
			{
				return this._onay;
			}
			set
			{
				if ((this._onay != value))
				{
					this.OnonayChanging(value);
					this.SendPropertyChanging();
					this._onay = value;
					this.SendPropertyChanged("onay");
					this.OnonayChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
